name: Flutter CI/CD and Firebase Distribution

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java Environment
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Set up Flutter Environment
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.0'

    - name: Install Flutter Dependencies
      run: flutter pub get

    - name: Build Flutter APK
      run: flutter build apk

    - name: Distribute APK to Firebase
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: build/app/outputs/flutter-apk/app-release.apk

