name: Build and Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
      
    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.0'  # Replace with your Flutter version
      
    - name: Get Flutter packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Distribute APK to Firebase App Distribution
      uses: w9jds/firebase-action@v2.1.1
      with:
        args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
