name: Flutter App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        run: |
          curl -sL https://sdk.flutter.dev/flutter-linux-x64.tar.xz | tar -xf -
          ./flutter/bin/flutter doctor
      - name: Install dependencies
        run: flutter pub get
      - name: Build app
        run: flutter build apk
      - name: Deploy to Firebase
        run: |
          firebase app distribution upload --app my-app \
            --apk build/app/outputs/apk/release/app-release.apk \
            --release-notes "This is a release note for my app."
            --token $FIREBASE_TOKEN
