name: Flutter App Distribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: flutter/flutter-action@v1
        with:
          flutter-version: "3.0.0"
      - name: Install dependencies
        run: flutter pub get
      - name: Build app
        run: flutter build apk
      - name: Deploy to Firebase
        run: |
          firebase app distribution upload --app my-app \
            --apk build/app/outputs/apk/release/app-release.apk \
            --release-notes "This is a release note for my app."
            --token $FIREBASE_TOKEN
