name: Flutter Android Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        run: |
          curl -sL https://sdk.flutter.dev/flutter-linux-x64.tar.xz | tar -xf -
          export PATH="$HOME/flutter/bin:$PATH"

      - name: Flutter Doctor
        run: flutter doctor

      - name: Build Flutter App
        run: flutter build apk

      - name: Deploy Flutter App to Firebase
        run: |
          firebase appdistribution:distribute \
            --app <YOUR_FIREBASE_APP_ID> \
            --apk build/app/outputs/apk/release/app-release.apk
            --token $FIREBASE_TOKEN
